font_family                 JetBrainsMono Nerd Font
enable_audio_bell           no
visual_bell_duration        0.2
bell_path                   /usr/share/sounds/freedesktop/stereo/bell.oga
background                  #161616
copy_on_select              yes
window_padding_width        12
adjust_line_height          1
adjust_column_width         0